using UnityEngine;
using DG.Tweening;
using System;
using System.Collections.Generic;
using WheelGame.Contracts.Rewards;
using WheelGame.Contracts.Services;
using WheelGame.Gameplay.Wheel.Controllers;
using WheelGame.UI.Components;

/// <summary>
/// Coordinates mechanical physics simulations, layout alignment algorithms, and multi-layered sequence visual transformations for the reward wheel framework.
/// </summary>
namespace WheelGame.Gameplay.Wheel
{
public class WheelManager : MonoBehaviour, IWheelService
{
    #region Events

    // Observer pattern parameter tracking notification arrays
    public event Action<int> OnSpinComplete;

    #endregion

    #region Serialized References

    [Header("Render Pipelines")]
    [SerializeField] private UnityEngine.UI.Image wheelBaseImage; 
    [SerializeField] private UnityEngine.UI.Image indicatorImage; 
    [SerializeField] private UnityEngine.UI.Image wheelGlowImage; 

    [Header("Structural Hierarchies")]
    [SerializeField] private RectTransform wheelContainer; 
    [SerializeField] private WheelSliceUI slicePrefab; 

    [Header("Mechanical Physics Tuning")]
    [SerializeField] private int numberOfSlices = 8;
    [SerializeField] private int minSpins = 5;
    [SerializeField] private float spinDuration = 3f;

    #endregion

    #region Runtime Controllers

    private WheelSpinController _wheelSpinController;
    private WheelLayoutController _wheelLayoutController;
    private WheelAuraController _wheelAuraController;
    private WheelVisualController _wheelVisualController;
    private WheelPositionResolver _wheelPositionResolver;

    #endregion

    #region Unity Lifecycle

    private void Awake()
    {
        _wheelAuraController = new WheelAuraController(wheelGlowImage);
        _wheelVisualController = new WheelVisualController(wheelBaseImage, indicatorImage, _wheelAuraController);
        _wheelLayoutController = new WheelLayoutController(wheelContainer, slicePrefab);
        _wheelSpinController = new WheelSpinController(wheelContainer, minSpins, spinDuration);
        _wheelPositionResolver = new WheelPositionResolver(wheelContainer);
    }

    #endregion

    #region IWheelService

    /// <summary>
    /// Simulates mechanical rotation arrays using pre-calculated target parameters. Fires a completion callback upon absolute termination.
    /// </summary>
    /// <param name="resultIndex">The targeted award data slice entry mathematically generated by the validation engine.</param>
    public void SpinWheel(int resultIndex)
    {
        _wheelSpinController?.SpinWheel(numberOfSlices, resultIndex, landedIndex => OnSpinComplete?.Invoke(landedIndex));
    }

    /// <summary>
    /// Flushes leftover slice transforms, rebuilds the sector array components dynamically, and distributes configured items step-by-step.
    /// </summary>
    /// <param name="rewards">The active collection dataset representing the valid 8 slices for the current level pool.</param>
    public void SetupWheel(List<IRewardAction> rewards)
    {
        numberOfSlices = _wheelLayoutController != null
            ? _wheelLayoutController.BuildSlices(rewards)
            : rewards.Count;
    }

    /// <summary>
    /// Calculates and returns the screen coordinates of the absolute winning sector position (positioned at top dead center - 12 o'clock).
    /// Used directly as a vector seed source point for flying particle animation layers.
    /// </summary>
    /// <returns>The transform world space vector position coordinates matching active selection pins.</returns>
    public Vector3 GetWinningSlicePosition()
    {
        return _wheelPositionResolver != null
            ? _wheelPositionResolver.GetWinningSlicePosition()
            : wheelContainer.position + new Vector3(0, 300f, 0);
    }

    /// <summary>
    /// Triggers visual sequence cross-fades and handles pulsing glow light states across progression changes.
    /// </summary>
    public void UpdateWheelVisuals(Sprite newWheelSprite, Sprite newIndicatorSprite, bool isSafeZone, bool isSuperZone)
    {
        _wheelVisualController?.UpdateWheelVisuals(newWheelSprite, newIndicatorSprite, isSafeZone, isSuperZone);
    }

    #endregion

#if UNITY_EDITOR
    #region Editor Validation

    private void OnValidate()
    {
        if (wheelBaseImage == null)
        {
            Debug.LogWarning("[WheelManager] wheelBaseImage reference is missing.", this);
        }

        if (indicatorImage == null)
        {
            Debug.LogWarning("[WheelManager] indicatorImage reference is missing.", this);
        }

        if (wheelGlowImage == null)
        {
            Debug.LogWarning("[WheelManager] wheelGlowImage reference is missing.", this);
        }

        if (wheelContainer == null)
        {
            Debug.LogWarning("[WheelManager] wheelContainer reference is missing.", this);
        }

        if (slicePrefab == null)
        {
            Debug.LogWarning("[WheelManager] slicePrefab reference is missing.", this);
        }
    }

    #endregion
#endif
}
}