using UnityEngine;
using DG.Tweening;
using System;
using System.Collections.Generic;

/// <summary>
/// Coordinates mechanical physics simulations, layout alignment algorithms, and multi-layered sequence visual transformations for the reward wheel framework.
/// </summary>
public class WheelManager : MonoBehaviour
{
    // Observer pattern parameter tracking notification arrays
    public event Action<int> OnSpinComplete;

    [Header("Render Pipelines")]
    [SerializeField] private UnityEngine.UI.Image wheelBaseImage; 
    [SerializeField] private UnityEngine.UI.Image indicatorImage; 
    [SerializeField] private UnityEngine.UI.Image wheelGlowImage; 

    [Header("Structural Hierarchies")]
    [SerializeField] private RectTransform wheelContainer; 
    [SerializeField] private WheelSliceUI slicePrefab; 

    [Header("Mechanical Physics Tuning")]
    [SerializeField] private int numberOfSlices = 8;
    [SerializeField] private int minSpins = 5;
    [SerializeField] private float spinDuration = 3f;

    /// <summary>
    /// Simulates mechanical rotation arrays using pre-calculated target parameters. Fires a completion callback upon absolute termination.
    /// </summary>
    /// <param name="resultIndex">The targeted award data slice entry mathematically generated by the validation engine.</param>
    public void SpinWheel(int resultIndex)
    {
        // FIXED CRITICAL BUG: The wheel no longer dictates random outcomes natively. It obeys structural state directives.
        
        // Calculate structural sector rotational offsets accurately across standard Z angular units
        float sliceAngle = 360f / numberOfSlices;
        float offsetAngle = (numberOfSlices - resultIndex) * sliceAngle;
        float targetAngle = (minSpins * 360f) + offsetAngle;

        // Reset tracking orientations flatly before writing ongoing animation paths
        wheelContainer.localEulerAngles = Vector3.zero;

        // Execute rotation simulation sequences through the rendering container
        wheelContainer.DORotate(new Vector3(0, 0, -targetAngle), spinDuration, RotateMode.FastBeyond360)
            .SetEase(Ease.OutElastic, 1.5f, 1f)
            .OnComplete(() => 
            {
                Debug.Log($"[WheelManager] Rotation completed. Landed Index Marker: {resultIndex}");
                // Broadcast final validation values to tracking state modules
                OnSpinComplete?.Invoke(resultIndex);
            });
    }

    /// <summary>
    /// Flushes leftover slice transforms, rebuilds the sector array components dynamically, and distributes configured items step-by-step.
    /// </summary>
    /// <param name="rewards">The active collection dataset representing the valid 8 slices for the current level pool.</param>
    public void SetupWheel(List<IRewardAction> rewards)
    {
        numberOfSlices = rewards.Count;

        // 1. Flush deprecated child entries instantly from the display transform container
        foreach (Transform child in wheelContainer)
        {
            Destroy(child.gameObject);
        }

        // 2. Generate active entries and orient them geometrically around a polar axis circle
        float sliceAngle = 360f / numberOfSlices;

        for (int i = 0; i < numberOfSlices; i++)
        {
            WheelSliceUI newSlice = Instantiate(slicePrefab, wheelContainer);
            newSlice.Configure(rewards[i]);

            // Shift rotation layouts iteratively to position elements natively into unified circular shapes
            newSlice.transform.localEulerAngles = new Vector3(0, 0, -i * sliceAngle);
        }
    }

    /// <summary>
    /// Calculates and returns the screen coordinates of the absolute winning sector position (positioned at top dead center - 12 o'clock).
    /// Used directly as a vector seed source point for flying particle animation layers.
    /// </summary>
    /// <returns>The transform world space vector position coordinates matching active selection pins.</returns>
    public Vector3 GetWinningSlicePosition()
    {
        // Note: Currently maps directly directly onto an offset reference node above the origin pivot
        return wheelContainer.position + new Vector3(0, 300f, 0); 
    }

    /// <summary>
    /// Triggers visual sequence cross-fades and handles pulsing glow light states across progression changes.
    /// </summary>
    public void UpdateWheelVisuals(Sprite newWheelSprite, Sprite newIndicatorSprite, bool isSafeZone, bool isSuperZone)
    {
        // Performance guard: If the backing texture profile has not changed, execute a small impact bump animation and exit early
        if (wheelBaseImage.sprite == newWheelSprite)
        {
            wheelBaseImage.transform.DOPunchScale(Vector3.one * 0.05f, 0.3f, 10, 1f);
            return;
        }
        
        wheelBaseImage.transform.DOKill();
        if (indicatorImage != null) indicatorImage.transform.DOKill();

        Sequence seq = DOTween.Sequence();

        // Phase 1: Collapse structural elements inwards out of active view ranges
        seq.Append(wheelBaseImage.transform.DOScale(Vector3.zero, 0.2f).SetEase(Ease.InBack));
        if (indicatorImage != null)
        {
            seq.Join(indicatorImage.transform.DOScale(Vector3.zero, 0.2f).SetEase(Ease.InBack));
        }

        // Phase 2: Perform atomic image updates safely while components are scaled to zero
        seq.AppendCallback(() => 
        {
            wheelBaseImage.sprite = newWheelSprite;
            if (indicatorImage != null) indicatorImage.sprite = newIndicatorSprite;
        });

        // Phase 3: Pop newly assigned display elements back into active layout configurations using an elastic rebound curve
        seq.Append(wheelBaseImage.transform.DOScale(Vector3.one, 0.5f).SetEase(Ease.OutBack));
        if (indicatorImage != null)
        {
            seq.Join(indicatorImage.transform.DOScale(Vector3.one, 0.5f).SetEase(Ease.OutBack));
        }

        // Add a flashy spin twist to add production flair during progression entry transitions
        seq.Join(wheelBaseImage.transform.DORotate(new Vector3(0, 0, -360), 0.5f, RotateMode.FastBeyond360).SetRelative());
        
        ManageAuraEffects(isSafeZone, isSuperZone);
    }

    /// <summary>
    /// Manages backing particle neon alpha levels and drives looping sinus scaling pulse workflows for bonus tiers.
    /// </summary>
    private void ManageAuraEffects(bool isSafeZone, bool isSuperZone)
    {
        if (wheelGlowImage == null) return;
        
        wheelGlowImage.DOKill(); 
        wheelGlowImage.transform.DOKill();
        
        if (isSafeZone || isSuperZone)
        {
            if (isSuperZone)
            {
                wheelGlowImage.color = new Color(1f, 0.8f, 0f, 0f); // Gold Amber Glow
            }
            else if (isSafeZone)
            {
                wheelGlowImage.color = new Color(0.85f, 0.85f, 0.9f, 0f); // Silver Platinum Glow
            }

            Sequence auraSeq = DOTween.Sequence();
            auraSeq.Append(wheelGlowImage.DOFade(0.6f, 1f)); 
            
            auraSeq.Join(wheelGlowImage.transform.DOScale(1.1f, 1.5f)
                         .SetLoops(-1, LoopType.Yoyo)
                         .SetEase(Ease.InOutSine));
        }
        else
        {
            wheelGlowImage.DOFade(0f, 0.5f);
            wheelGlowImage.transform.localScale = Vector3.one;
        }
    }
}